name: E2E (WebdriverIO)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      NODE_ENV: test
      USERNAME_LOGIN: ${{ secrets.USERNAME_LOGIN || 'standard_user' }}
      PASSWORD_LOGIN: ${{ secrets.PASSWORD_LOGIN || 'secret_sauce' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: npm ci

      - name: Run E2E
        run: npm run test:e2e

      - name: Upload test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            ./allure-results/**
            ./wdio-*.log
            ./errorShots/**
          if-no-files-found: ignore
          retention-days: 7